### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Vaults1** [BoxOfDevs/Resources#1]
You could put it in a special folder in JenkinsResources, then rename it to resources so we don't have too many repo's.

**Comment by HimbeersaftLP** [comment]
It would make more sense to put the JenkinsResources into this repo...

**Comment by Vaults1** [comment]
I can't as I have no git access right now.

**Comment by HimbeersaftLP** [comment]
I'll move all files from JenkinsResources to the subfolder "Jenkins" here then, okay?

**Comment by Vaults1** [comment]
👍
